{
  parserClass="net.patrickpfeifer.intellij.plugins.hellodsl.HelloDslParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="HelloDsl"
  psiImplClassSuffix="Impl"
  psiPackage="net.patrickpfeifer.intellij.plugins.hellodsl.psi"
  psiImplPackage="net.patrickpfeifer.intellij.plugins.hellodsl.psi.impl"

  elementTypeHolderClass="net.patrickpfeifer.intellij.plugins.hellodsl.psi.HelloDslTypes"
  elementTypeClass="net.patrickpfeifer.intellij.plugins.hellodsl.psi.HelloDslElementType"
  tokenTypeClass="net.patrickpfeifer.intellij.plugins.hellodsl.psi.HelloDslElementType"
}

helloDslFile ::= item*

private item ::= (key_value|COMMENT|CRLF)

key_value ::= (KEY? SEPARATOR VALUE?) | KEY
